### ISSUE TITLE
the size of the "size brush" is too small on mobile

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/CountDownDevFest2017#6]
![image](https://user-images.githubusercontent.com/516360/31670747-96bc6afc-b358-11e7-8022-8941e7905023.png)

**Comment by jefBinomed** [comment]
Fix with remove of healing button (eraser) : https://github.com/GDG-Nantes/CountDownDevFest2017/commit/d3efe21d4f45a5e0d095345cf484b937a66b826b
