### ISSUE TITLE
Strange message after login

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/CountDownDevFest2017#7]
After giving my credentials, I am redirected on this weird page : 
![image](https://user-images.githubusercontent.com/516360/31670852-d80ac4f4-b358-11e7-8097-17078dfc2e9a.png)

Then I am automatically redirected to the "help page". 
It should be better to be redirected directly to the "help page"

**Comment by jefBinomed** [comment]
Won't change due cinematic not trival, it finally change  after few seconds, i will deal with others bugs
