### ISSUE TITLE
French labels

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/CountDownDevFest2017#8]
Some french labels in the app : 
![image](https://user-images.githubusercontent.com/516360/31670976-27541420-b359-11e7-9960-53597e1b0d87.png)

**Comment by jefBinomed** [comment]
fixé avec le commit https://github.com/GDG-Nantes/CountDownDevFest2017/commit/d3efe21d4f45a5e0d095345cf484b937a66b826b
